// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/migrações usam a conexão DIRETA (porta 5432) no Supabase;
    // o pgbouncer (6543) não suporta comandos de migração.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
